trigger:
- main

resources:
- repo: self

pool: personal-devices

variables:
  imageRepository: 'microservicedemo'
  containerRegistry: 'pwcacr12345unique.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    

    - task: Bash@3
      displayName: Build and push with Podman
      inputs:
        targetType: 'inline'
        script: |
          REGISTRY_URL="$(containerRegistry)"
          USERNAME="$(ACR_USERNAME)"
          PASSWORD="$(ACR_PASSWORD)"
          
          echo "Registry URL: $REGISTRY_URL"
          
          # Log in to the container registry
          echo "$PASSWORD" | podman login -u "$USERNAME" --password-stdin "$REGISTRY_URL"
          
          # Build the image with the full repository name including the registry
          FULL_IMAGE_NAME="$REGISTRY_URL/$(imageRepository):$(tag)"
          echo "Building image: $FULL_IMAGE_NAME"
          
          podman build --platform linux/x86_64 -t "$FULL_IMAGE_NAME" -f $(dockerfilePath) .
          
          # Push the image to the registry
          echo "Pushing image to registry..."
          podman push "$FULL_IMAGE_NAME"

    - script: |
        echo "$(tag)" > image_tag.txt
      displayName: Write image tag artifact to a file

    - publish: image_tag.txt
      artifact: image-tag
      displayName: Publish image tag artifact



