apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: python-ms
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: pwcacr12345unique.azurecr.io/microservice-demo:3
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /users
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /users
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: python-ms
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
    - port: 80
      targetPort: 5000


